name: Collect Git Info
description: Collect Git repository information for Symbiotic scans

outputs:
  remote_url:
    description: The remote URL of the Git repository
  first_commit_sha:
    description: The SHA of the first commit in the repository
  latest_commit_sha:
    description: The SHA of the latest commit in the repository
  current_branch:
    description: The current branch name

runs:
  using: "composite"
  steps:
    - name: Collect git info
      id: collect-git-info
      shell: bash
      run: |
        echo -e "\033[1;34mâ­ Collecting git information...\033"

        remote_url="$(git config --get remote.origin.url)"
        first_commit_sha="$(git rev-list --max-parents=0 HEAD | head -n 1)"
        latest_commit_sha="$(git rev-parse HEAD)"
        current_branch="$(git branch --show-current)"

        echo "remote_url=$remote_url" >> "$GITHUB_OUTPUT"
        echo "first_commit_sha=$first_commit_sha" >> "$GITHUB_OUTPUT"
        echo "latest_commit_sha=$latest_commit_sha" >> "$GITHUB_OUTPUT"
        echo "current_branch=$current_branch" >> "$GITHUB_OUTPUT"
