name: Symbiotic Standard Scan
description: Scan the repository for vulnerabilities
inputs:
  api-token:
    description: Symbiotic Organization Access Token
    required: true
  scan-type:
    description: Type of scan to run
    required: false
    default: "all"
    options:
      - infra
      - code
      - all
  upload-results:
    description: Whether to upload the scan results to Symbiotic
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Collect git info
      id: git-info
      if: inputs.upload-results == 'true'
      shell: bash
      run: |
        source ${{ github.action_path }}/../scripts/collect-git-info.sh
        collect_git_info "git_info"

    - name: Run Code Scan
      id: code-scan
      if: inputs.scan-type == 'code' || inputs.scan-type == 'all'
      continue-on-error: true
      env:
        SYMBIOTIC_API_TOKEN: ${{ inputs.api-token }}
        SYMBIOTIC_TARGET_API: https://api.preprod.symbioticsec.ai
      shell: bash
      run: |
        echo -e "\033[1;36m💻 Running code scan...\033[0m"
        if [[ "${{ inputs.upload-results }}" == "true" ]]; then
          symbiotic-cli ci code ./ \
            --git-remote-url "${{ env.git_info_remote_url }}" \
            --git-first-commit-sha "${{ env.git_info_first_commit_sha }}" \
            --git-latest-commit-sha "${{ env.git_info_latest_commit_sha }}" \
            --git-default-branch "${{ github.event.repository.default_branch }}" \
            --git-current-branch "${{ env.git_info_current_branch }}"
        else
          symbiotic-cli ci code ./ --skip-upload-results
        fi

    - name: Run Infra Scan
      id: infra-scan
      if: inputs.scan-type == 'infra' || inputs.scan-type == 'all'
      continue-on-error: true
      env:
        SYMBIOTIC_API_TOKEN: ${{ inputs.api-token }}
        SYMBIOTIC_TARGET_API: https://api.preprod.symbioticsec.ai
      shell: bash
      run: |
        echo -e "\033[1;35m🏗️  Running infrastructure scan...\033[0m"
        if [[ "${{ inputs.upload-results }}" == "true" ]]; then
          symbiotic-cli ci infra ./ \
            --git-remote-url "${{ env.git_info_remote_url }}" \
            --git-first-commit-sha "${{ env.git_info_first_commit_sha }}" \
            --git-latest-commit-sha "${{ env.git_info_latest_commit_sha }}" \
            --git-default-branch "${{ github.event.repository.default_branch }}" \
            --git-current-branch "${{ env.git_info_current_branch }}"
        else
          symbiotic-cli ci infra ./ --skip-upload-results
        fi

    - name: Check Results
      shell: bash
      run: |
        # Check if any scan failed and exit with code 1
        if [[ "${{ steps.code-scan.outcome }}" == "failure" ]] || [[ "${{ steps.infra-scan.outcome }}" == "failure" ]]; then
          exit 1
        fi
