name: Symbiotic Scan
description: Scan the repository for vulnerabilities and misconfigurations
inputs:
  api-token:
    description: Symbiotic Organization Access Token
    required: true
  scan-type:
    description: Type of scan to run
    required: false
    default: "all"
    options:
      - infra
      - code
      - all
  upload-results:
    description: Whether to upload the scan results to Symbiotic
    required: false
    default: "true"
  diff-scan:
    description: Whether to run a diff scan (only display introduced vulnerabilities)
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install Symbiotic CLI
      shell: bash
      run: |
        echo -e "\033[1;34m🔧 Installing Symbiotic CLI...\033[0m"
        curl -sSL https://github.com/SymbioticSec/cli/releases/download/pro-1463-beta7/install.sh | bash
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV
    
    - name: Run Standard Scan
      if: ${{ github.event_name != 'pull_request' || inputs.diff-scan == 'false' }}
      uses: SymbioticSec/actions/standard-scan@${{ github.action_ref }}
      with:
        api-token: ${{ inputs.api-token }}
        scan-type: ${{ inputs.scan-type }}
        upload-results: ${{ inputs.upload-results }}

    - name: Run PR Diff Scan
      if: ${{ github.event_name == 'pull_request' && inputs.diff-scan == 'true' }}
      uses: SymbioticSec/actions/pr-scan@${{ github.action_ref }}
      with:
        api-token: ${{ inputs.api-token }}
        scan-type: ${{ inputs.scan-type }}
        upload-results: ${{ inputs.upload-results }}
