name: Symbiotic Scan
description: Scan the repository for vulnerabilities and misconfigurations
inputs:
  api-token:
    description: Symbiotic Organization Access Token
    required: true
  scan-type:
    description: Type of scan to run
    required: false
    default: 'all'
    options:
      - infra
      - code
      - all

runs:
  using: 'composite'
  steps:
    - name: Install Symbiotic CLI
      shell: bash
      run: |
        curl -sSL https://github.com/SymbioticSec/cli/releases/latest/download/install.sh | bash
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV

    - name: Run Code Scan
      id: code-scan
      if: inputs.scan-type == 'code' || inputs.scan-type == 'all'
      continue-on-error: true
      env:
        SYMBIOTIC_API_TOKEN: ${{ inputs.api-token }}
      shell: bash
      run: |
        symbiotic-cli ci code ./

    - name: Run Infra Scan
      id: infra-scan
      if: inputs.scan-type == 'infra' || inputs.scan-type == 'all'
      continue-on-error: true
      env:
        SYMBIOTIC_API_TOKEN: ${{ inputs.api-token }}
      shell: bash
      run: |
        symbiotic-cli ci infra ./

    - name: Check Results
      shell: bash
      run: |
        # Check if any scan failed and exit with code 1
        if [[ "${{ steps.code-scan.outcome }}" == "failure" ]] || [[ "${{ steps.infra-scan.outcome }}" == "failure" ]]; then
          exit 1
        fi
